### PR TITLE
feat(brackets): remove brackets and replace them by colons

### PR DESCRIPTION
**Pull request by Moundlen**
Remove brakets and replace them by colons so that postman understands and treats them as a path paramater, marked them as optionnal or required in the description

/example/{id}/{page?}
will be replaced by /example/:id/:page in postman
id will be marked as (Required) and page will be marked as (Optional) in the postman variable description

### CODE REVIEW

**Comment by Moundlen** [comment]
Just thought of something this change will not work on routes like /api/posts/{post:slug} will edit and do another pull request

https://laravel.com/docs/7.x/routing#implicit-binding

**Comment by profclems** [comment]
> Just thought of something this change will not work on routes like /api/posts/{post:slug} will edit and do another pull request
> 
> https://laravel.com/docs/7.x/routing#implicit-binding

I realized this too while reviewing the PR but I wanted to be sure

**Comment by Moundlen** [comment]
Should be fixed now, I upgraded the requirements since some code was not compatible with php 7.0 so upgraded to 7.1 added the ext-mbstring since it was missing and upgraded some comments. Also changed route name back to what it was before

**Review by profclems — APPROVED** [review]
LGTM! 

Thanks @Spacegame66  for taking this on

**Comment by Moundlen** [comment]
Thanks and thank you for the great package

**Pull request merged**
